FROM debian:bookworm

# Install build tools
RUN apt update \
  && apt install -y build-essential cmake wget git gawk libzstd-dev

# Install MPICH
RUN apt install -y mpich

# Install Clang
RUN apt install -y clang libomp-dev

# Install StarPU
RUN apt install -y libstarpu-dev pkgconf

# Install HTF

RUN git clone https://github.com/trahay/Hierarchical-Trace-Format.git htf \
&& (mkdir htf/build && \
    cd htf/build && \
    cmake .. \
    -DENABLE_OTF2=ON \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    && make install)

# Install EZTrace
RUN git clone -b eztrace-2.1-dev https://gitlab.com/eztrace/eztrace.git \
&& ( mkdir eztrace/build && cd eztrace/build &&  \
   cmake .. \
   -DENABLE_BIN_INSTRUMENTATION=OFF \
   -DEZTRACE_ENABLE_MPI=ON -DMPI_LINK_FLAGS="-fopenmp" \
   -DEZTRACE_ENABLE_OMPT=ON\
   -DEZTRACE_ENABLE_MEMORY=ON  \
   -DEZTRACE_ENABLE_STARPU=ON \
   -DCMAKE_C_COMPILER=clang-14 \
   && make -j 4 \
   && make install)
